#!/bin/sh
set -e

case "$1" in
    purge)
        # Remove keymap config if it exists
        rm -f /etc/dictacode/keymap.conf
        # Remove config directory if empty
        rmdir /etc/dictacode 2>/dev/null || true
        # Remove hid directory
        rm -rf /opt/dictacode/hid
        # Remove opt directory if empty
        rmdir /opt/dictacode 2>/dev/null || true
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
