#!/bin/bash
# =============================================================================
# setup-sudoers-dictacode.sh - Configure passwordless sudo for dictacode user
# =============================================================================
#
# This script configures NOPASSWD sudo permissions for the dictacode user
# to enable remote deployment and service management without password prompts.
#
# USAGE:
#   # Copy to remote device and run with root privileges:
#   scp -O tools/setup-sudoers-dictacode.sh dictacode-stt:/tmp/
#   ssh dictacode-stt "sudo bash /tmp/setup-sudoers-dictacode.sh"
#
# PERMISSIONS GRANTED:
#   - systemctl: daemon-reload, start/stop/restart/status dictacode-* services
#   - journalctl: view all logs
#   - apt: update, install packages (including from /tmp/*.deb)
#   - dpkg: install packages
#   - chmod/chown: /dev/serial* and /dev/hidg* devices
#
# =============================================================================

set -euo pipefail

SUDOERS_FILE="/etc/sudoers.d/dictacode-deploy"
SUDOERS_USER="${1:-dictacode}"

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root (use sudo)"
    exit 1
fi

echo "=== Setting up sudoers for user: $SUDOERS_USER ==="

# Create sudoers content
cat > /tmp/dictacode-sudoers << SUDOERS
# =============================================================================
# dictacode deployment permissions
# Generated by setup-sudoers-dictacode.sh
# =============================================================================

# System management - reboot/shutdown
$SUDOERS_USER ALL=(ALL) NOPASSWD: /sbin/reboot
$SUDOERS_USER ALL=(ALL) NOPASSWD: /sbin/shutdown *

# Service management - systemctl
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl daemon-reload
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl restart dictacode-stt
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl restart dictacode-hid
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl restart dictacode-*
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl start dictacode-stt
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl start dictacode-hid
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl start dictacode-*
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl stop dictacode-stt
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl stop dictacode-hid
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl stop dictacode-*
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl status dictacode-*
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/systemctl status *

# Log viewing - journalctl
$SUDOERS_USER ALL=(ALL) NOPASSWD: /bin/journalctl *

# Package management - apt
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/apt update
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/apt install -y *
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/apt install -y --allow-downgrades *
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/apt install -y /tmp/*.deb
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/apt install /tmp/*.deb
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/apt --fix-broken install -y

# Package management - dpkg
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/dpkg *
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/dpkg -i *

# Device permissions - serial ports
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/chmod * /dev/serial*
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/chown * /dev/serial*

# Device permissions - HID gadget
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/chmod * /dev/hidg*
$SUDOERS_USER ALL=(ALL) NOPASSWD: /usr/bin/chown * /dev/hidg*
SUDOERS

echo "Installing sudoers file to $SUDOERS_FILE..."

# Install with correct permissions
cp /tmp/dictacode-sudoers "$SUDOERS_FILE"
chmod 0440 "$SUDOERS_FILE"
chown root:root "$SUDOERS_FILE"

# Validate syntax
if visudo -c -f "$SUDOERS_FILE"; then
    echo "✓ Sudoers file installed and validated: $SUDOERS_FILE"
    echo ""
    echo "Permissions granted to $SUDOERS_USER:"
    grep "^$SUDOERS_USER" "$SUDOERS_FILE" | sed 's/^/  /'
else
    echo "✗ Sudoers syntax error! Removing invalid file."
    rm -f "$SUDOERS_FILE"
    exit 1
fi

# Clean up
rm -f /tmp/dictacode-sudoers

echo ""
echo "=== Setup complete ==="
echo "Test with: sudo -l -U $SUDOERS_USER"
